env:
  node: true
  es2020: true
  jest: true
extends:
  - "eslint:recommended"
  - "prettier"
parserOptions:
  ecmaVersion: 11
  sourceType: module
globals:
  mockConnect: readonly
rules:
  accessor-pairs: error
  array-bracket-newline: "off" # Off for prettier
  array-bracket-spacing: "off" # Off for prettier
  array-callback-return: error
  array-element-newline: "off" # Off for prettier
  arrow-body-style: "off"
  arrow-parens: "off" # Off for prettier
  arrow-spacing: "off" # Off for prettier
  block-scoped-var: error
  block-spacing: "off" # Off for prettier
  brace-style: "off" # Off for prettier
  callback-return: error
  camelcase: error
  capitalized-comments:
    - error
    - always
  class-methods-use-this: error
  comma-dangle: "off"
  comma-spacing: "off" # Off for prettier
  comma-style: "off" # Off for prettier
  complexity: error
  computed-property-spacing: "off" # Off for prettier
  consistent-return: "off"
  consistent-this: error
  curly: "off"
  default-case: error
  default-case-last: error
  default-param-last: error
  dot-location: "off" # Off for prettier
  dot-notation:
    - error
    - allowKeywords: true
  eol-last: "off" # Off for prettier
  eqeqeq: error
  func-call-spacing: "off" # Off for prettier
  func-name-matching: error
  func-names: "off"
  func-style:
    - error
    - expression
  function-paren-newline: "off" # Off for prettier
  generator-star-spacing: "off" # Off for prettier
  global-require: error
  grouped-accessor-pairs: error
  guard-for-in: error
  handle-callback-err: error
  id-blacklist: error
  id-denylist: error
  id-length: "off"
  id-match: error
  implicit-arrow-linebreak: "off" # Off for prettier
  indent: "off"
  indent-legacy: "off"
  init-declarations: "off"
  jsx-quotes: "off" # Off for prettier
  key-spacing: "off" # Off for prettier
  keyword-spacing: "off"
  line-comment-position: error
  linebreak-style: "off" # Off for prettier
  lines-around-comment: "off" # Off for prettier
  lines-around-directive: error
  lines-between-class-members: error
  max-classes-per-file: error
  max-depth: error
  max-len: "off"
  max-lines:
    - error
    - max: 350
  max-lines-per-function: "off"
  max-nested-callbacks: error
  max-params: "off"
  max-statements: "off"
  max-statements-per-line: error
  multiline-comment-style:
    - error
    - separate-lines
  multiline-ternary: "off" # Off for prettier
  new-cap: "off"
  new-parens: "off" # Off for prettier
  newline-after-var: "off"
  newline-before-return: "off"
  newline-per-chained-call: "off"
  no-alert: error
  no-array-constructor: error
  no-await-in-loop: error
  no-bitwise: error
  no-buffer-constructor: error
  no-caller: error
  no-catch-shadow: error
  no-confusing-arrow: "off" # Off for prettier
  no-console: "off"
  no-constructor-return: error
  no-continue: error
  no-div-regex: error
  no-duplicate-imports: error
  no-else-return: error
  no-empty-function: error
  no-eq-null: error
  no-eval: error
  no-extend-native: error
  no-extra-bind: error
  no-extra-label: error
  no-extra-parens: "off" # Off for prettier
  no-floating-decimal: "off" # Off for prettier
  no-implicit-coercion: error
  no-implicit-globals: error
  no-implied-eval: error
  no-inline-comments: error
  no-invalid-this: error
  no-iterator: error
  no-label-var: error
  no-labels: error
  no-lone-blocks: error
  no-lonely-if: error
  no-loop-func: error
  no-loss-of-precision: error
  no-magic-numbers: "off"
  no-mixed-operators: "off" # Off for prettier
  no-mixed-requires: error
  no-multi-assign: error
  no-multi-spaces: "off" # Off for prettier
  no-multi-str: error
  no-multiple-empty-lines: "off" # Off for prettier
  no-native-reassign: error
  no-negated-condition: error
  no-negated-in-lhs: error
  no-nested-ternary: error
  no-new: error
  no-new-func: error
  no-new-object: error
  no-new-require: error
  no-new-wrappers: error
  no-octal-escape: error
  no-param-reassign: error
  no-path-concat: error
  no-plusplus: error
  no-process-env: "off"
  no-process-exit: error
  no-promise-executor-return: error
  no-proto: error
  no-restricted-exports: error
  no-restricted-globals: error
  no-restricted-imports: error
  no-restricted-modules: error
  no-restricted-properties: error
  no-restricted-syntax: error
  no-return-assign: error
  no-return-await: error
  no-script-url: error
  no-self-compare: error
  no-sequences: error
  no-shadow: "off"
  no-spaced-func: "off" # Off for prettier
  no-sync: "off"
  no-tabs: "off" # Off for prettier
  no-template-curly-in-string: error
  no-ternary: "off"
  no-throw-literal: error
  no-trailing-spaces: "off" # Off for prettier
  no-undef-init: error
  no-undefined: error
  no-underscore-dangle: "off"
  no-unmodified-loop-condition: error
  no-unneeded-ternary: error
  no-unreachable-loop: error
  no-unused-expressions: error
  no-use-before-define: "off"
  no-useless-backreference: error
  no-useless-call: error
  no-useless-computed-key: error
  no-useless-concat: error
  no-useless-constructor: error
  no-useless-rename: error
  no-useless-return: error
  no-var: error
  no-void: error
  no-warning-comments: error
  no-whitespace-before-property: "off" # Off for prettier
  nonblock-statement-body-position: "off" # Off for prettier
  object-curly-newline: "off" # Off for prettier
  object-curly-spacing: "off" # Off for prettier
  object-shorthand: error
  one-var: "off"
  one-var-declaration-per-line: "off" # Off for prettier
  operator-assignment: error
  operator-linebreak: "off" # Off for prettier
  padded-blocks: "off"
  padding-line-between-statements: error
  prefer-arrow-callback: "off"
  prefer-const: error
  prefer-destructuring: error
  prefer-exponentiation-operator: error
  prefer-named-capture-group: error
  prefer-numeric-literals: error
  prefer-object-spread: error
  prefer-promise-reject-errors: error
  prefer-reflect: "off"
  prefer-regex-literals: error
  prefer-rest-params: error
  prefer-spread: error
  prefer-template: error
  quote-props: "off"
  quotes: "off"
  radix: error
  require-atomic-updates: error
  require-await: error
  require-jsdoc: error
  require-unicode-regexp: "off"
  rest-spread-spacing: "off" # Off for prettier
  semi: "off"
  semi-spacing: "off" # Off for prettier
  semi-style: "off" # Off for prettier
  sort-keys: "off"
  sort-vars: error
  space-before-blocks: "off" # Off for prettier
  space-before-function-paren: "off" # Off for prettier
  space-in-parens: "off" # Off for prettier
  space-infix-ops: "off" # Off for prettier
  space-unary-ops: "off" # Off for prettier
  spaced-comment:
    - error
    - always
  strict: error
  switch-colon-spacing: "off" # Off for prettier
  symbol-description: error
  template-curly-spacing: "off" # Off for prettier
  template-tag-spacing: "off" # Off for prettier
  unicode-bom: "off" # Off for prettier
  valid-jsdoc: error
  vars-on-top: error
  wrap-iife: "off" # Off for prettier
  wrap-regex: "off" # Off for prettier
  yield-star-spacing: "off" # Off for prettier
  yoda:
    - error
    - never
